// lib/enums.ts

export const Position = {
  USER: "user",
  BOARD_MEMBER: "board_member",
  ADMIN: "admin",
} as const;

export const PositionLabels: Record<string, string> = {
    user: "General Member",
    board_member: "Board Member",
    admin: "Admin",
}

export const BoardPositions = {
  PRESIDENT: "president",
  INTERNAL_VICE_PRESIDENT: "internal_vice_president",
  EXTERNAL_VICE_PRESIDENT: "external_vice_president",
  ALUMNI_INDUSTRY_RELATIONS: "alumni_industry_relations",
  MENTORSHIP_COORDINATOR: "mentorship_coordinator",
  SECRETARY: "secretary",
  TREASURER: "treasurer",
  ACTIVITIES_COORDINATOR: "activities_coordinator",
  PUBLIC_RELATIONS: "public_relations",
  HISTORIAN: "historian",
} as const;

export const BoardPositionLabels: Record<string, string> = {
  president: "President",
  internal_vice_president: "Internal Vice President",
  external_vice_president: "External Vice President",
  alumni_industry_relations: "Alumni & Industry Relations",
  mentorship_coordinator: "Mentorship Coordinator",
  secretary: "Secretary",
  treasurer: "Treasurer",
  activities_coordinator: "Activities Coordinator",
  public_relations: "Public Relations",
  historian: "Historian",
};

export const Major = {
  BA_ART_HISTORY: "ba_art_history",
  BA_ASIAN_AMERICAN_STUDIES: "ba_asian_american_studies",
  BS_ATMOSPHERIC_OCEANIC_SCIENCES: "bs_atmospheric_oceanic_sciences",
  BS_ATMOSPHERIC_OCEANIC_SCIENCES_MATHEMATICS: "bs_atmospheric_oceanic_sciences_mathematics",
  BS_BIOCHEMISTRY: "bs_biochemistry",
  BS_BIOLOGY: "bs_biology",
  BS_BIOPHYSICS: "bs_biophysics",
  BA_BUSINESS_ECONOMICS: "ba_business_economics",
  BS_CHEMISTRY_MATERIALS_SCIENCE: "bs_chemistry_materials_science",
  BS_CLIMATE_SCIENCE: "bs_climate_science",
  BS_COGNITIVE_SCIENCE: "bs_cognitive_science",
  BA_COMMUNICATION: "ba_communication",
  BA_COMPARATIVE_LITERATURE: "ba_comparative_literature",
  BS_COMPUTATIONAL_SYSTEMS_BIOLOGY: "bs_computational_systems_biology",
  BS_DATA_THEORY: "bs_data_theory",
  BA_DISABILITY_STUDIES: "ba_disability_studies",
  BA_EARTH_ENVIRONMENTAL_SCIENCES: "ba_earth_environmental_science",
  BS_ECOLOGY_BEHAVIOR_EVOLUTION: "bs_ecology_behavior_evolution",
  BA_ECONOMICS: "ba_economics",
  BA_ENGLISH: "ba_english",
  BS_ENVIRONMENT_SCIENCES: "bs_environment_science",
  BA_GENDER_STUDIES: "ba_gender_studies",
  BS_GEOLOGY: "bs_geology",
  BA_HISTORY: "ba_history",
  BA_HUMAN_BIOLOGY_SOCIETY: "ba_human_biology_society",
  BS_HUMAN_BIOLOGY_SOCIETY: "bs_human_biology_society",
  BA_LABOR_STUDIES: "ba_labor_studies",
  BA_LINGUISTICS: "ba_linguistics",
  BA_LINGUISTICS_COMPUTER_SCIENCE: "ba_linguistics_computer_science",
  BS_MATHEMATICS: "bs_mathematics",
  BS_MATHEMATICS_APPLIED_SCIENCE: "bs_mathematics_applied_science",
  BS_MATHEMATICS_ECONOMICS: "bs_mathematics_economics",
  BS_MATHEMATICS_FINANCIAL_ACTUARIAL: "bs_mathematics_financial_actuarial",
  BS_MIMG: "bs_mimg",
  BS_MCDB: "bs_mcdb",
  BS_NEUROSCIENCE: "bs_neuroscience",
  BA_PHYSICS: "ba_physics",
  BS_PHYSICS: "bs_physics",
  BA_PHYSIOLOGICAL_SCIENCE: "ba_physiological_science",
  BA_POLITICAL_SCIENCE: "ba_political_science",
  BA_PSYCHOLOGY: "ba_psychology",
  BA_SOCIOLOGY: "ba_sociology",
  BS_AEROSPACE_ENGINEERING: "bs_aerospace_engineering",
  BS_BIOENGINEERING: "bs_bioengineering",
  BS_CHEMICAL_ENGINEERING: "bs_chemical_engineering",
  BS_CIVIL_ENGINEERING: "bs_civil_engineering",
  BS_COMPUTER_ENGINEERING: "bs_computer_engineering",
  BS_COMPUTER_SCIENCE: "bs_computer_science",
  BS_COMPUTER_SCIENCE_ENGINEERING: "bs_computer_science_engineering",
  BS_ELECTRICAL_ENGINEERING: "bs_electrical_engineering",
  BS_MATERIALS_ENGINEERING: "bs_materials_engineering",
  BS_MECHANICAL_ENGINEERING: "bs_mechanical_engineering",
  BA_PUBLIC_AFFAIRS: "ba_public_affairs",
  BA_FILM_TELEVISION: "ba_film_television",
  BA_THEATER: "ba_theater",
  BA_CONC_TFT: "ba_conc_tft",
  BA_EDUCATION: "ba_education",
  BA_PUBLIC_HEALTH: "ba_public_health",
  BS_PUBLIC_HEALTH: "bs_public_health",
  UNDECLARED: "undeclared",
  ADMIN: "admin",
} as const;

export const MajorLabels: Record<string, string> = {
  ba_art_history: "Art History",
  ba_asian_american_studies: "Asian American Studies",
  bs_atmospheric_oceanic_sciences: "Atmospheric & Oceanic Sciences",
  bs_atmospheric_oceanic_sciences_mathematics: "Atmospheric & Oceanic Sciences – Mathematics",
  bs_biochemistry: "Biochemistry",
  bs_biology: "Biology",
  bs_biophysics: "Biophysics",
  ba_business_economics: "Business Economics",
  bs_chemistry_materials_science: "Chemistry – Materials Science",
  bs_climate_science: "Climate Science",
  bs_cognitive_science: "Cognitive Science",
  ba_communication: "Communication",
  ba_comparative_literature: "Comparative Literature",
  bs_computational_systems_biology: "Computational & Systems Biology",
  bs_data_theory: "Data Theory",
  ba_disability_studies: "Disability Studies",
  ba_earth_environmental_science: "Earth & Environmental Sciences",
  bs_ecology_behavior_evolution: "Ecology, Behavior, & Evolution",
  ba_economics: "Economics",
  ba_english: "English",
  bs_environment_science: "Environmental Science",
  ba_gender_studies: "Gender Studies",
  bs_geology: "Geology",
  ba_history: "History",
  ba_human_biology_society: "Human Biology & Society (BA)",
  bs_human_biology_society: "Human Biology & Society (BS)",
  ba_labor_studies: "Labor Studies",
  ba_linguistics: "Linguistics",
  ba_linguistics_computer_science: "Linguistics & Computer Science",
  bs_mathematics: "Mathematics",
  bs_mathematics_applied_science: "Mathematics – Applied Science",
  bs_mathematics_economics: "Mathematics – Economics",
  bs_mathematics_financial_actuarial: "Mathematics – Financial Actuarial",
  bs_mimg: "Microbiology, Immunology, & Molecular Genetics (MIMG)",
  bs_mcdb: "Molecular, Cell, & Developmental Biology (MCDB)",
  bs_neuroscience: "Neuroscience",
  ba_physics: "Physics (BA)",
  bs_physics: "Physics (BS)",
  ba_physiological_science: "Physiological Science",
  ba_political_science: "Political Science",
  ba_psychology: "Psychology",
  ba_sociology: "Sociology",
  bs_aerospace_engineering: "Aerospace Engineering",
  bs_bioengineering: "Bioengineering",
  bs_chemical_engineering: "Chemical Engineering",
  bs_civil_engineering: "Civil Engineering",
  bs_computer_engineering: "Computer Engineering",
  bs_computer_science: "Computer Science",
  bs_computer_science_engineering: "Computer Science & Engineering",
  bs_electrical_engineering: "Electrical Engineering",
  bs_materials_engineering: "Materials Engineering",
  bs_mechanical_engineering: "Mechanical Engineering",
  ba_public_affairs: "Public Affairs",
  ba_film_television: "Film & Television",
  ba_theater: "Theater",
  ba_conc_tft: "TFT (Concentration)",
  ba_education: "Education",
  ba_public_health: "Public Health (BA)",
  bs_public_health: "Public Health (BS)",
  undeclared: "Undeclared",
  admin: "Admin",
};

// --- RESOURCE TYPES ---
export const ResourceType = {
  SCHOLARSHIP: "scholarship",
  CAREER: "career",
} as const;

export const ResourceTypeLabels: Record<string, string> = {
  scholarship: "Scholarship",
  career: "Career",
};

// Optional helper: get enum keys/values as arrays
export const enumToArray = <T extends Record<string, string>>(enumObj: T) =>
  Object.values(enumObj);
